# Generated by Django 2.2.6 on 2020-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('room_capacity', models.IntegerField()),
                ('room_projector', models.BooleanField()),
            ],
        ),
    ]
