# Generated by Django 2.2.6 on 2020-07-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservations_TB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
